/*
	Задание:
	Пусть в таблице users поля created_at и updated_at оказались незаполненными. 
    Заполните их текущими датой и временем.
*/

-- autogenerated code from alter table menu in MySQL Workbench
-- add columns created_at and updated_at with NULL value

/*
ALTER TABLE `users`
DROP COLUMN created_at;

ALTER TABLE `users`
DROP COLUMN updated_at;
*/

ALTER TABLE `users` 
ADD COLUMN `created_at` VARCHAR(45) NULL DEFAULT NULL AFTER `password_hash`,
ADD COLUMN `updated_at` VARCHAR(45) NULL DEFAULT NULL AFTER `created_at`;

UPDATE `users`
SET
	created_at = NOW(),
    updated_at = NOW();
    
DESCRIBE `users`;